#pragma once

// Includes.
#include "..\Contrib\Include\gl\glew.h"
#include "Utility.h"
#include <sstream>
#include <iostream>

/*
	Shader class that holds ID to a program object
	that is generated by loading and compiling the
	relevant shader codes from the given paths.
*/
class Shader
{
public:

// Variables

	GLuint program;

// Functions

	Shader();
	Shader(const GLchar* vertexPath, const GLchar* fragmentPath);
	Shader(const GLchar* vertexPath, const GLchar* geometryPath, const GLchar* fragmentPath);
	void Use(void);
	~Shader();
};